version: "3"
services:
  redis:
    image: redis
    container_name: cache
    networks:
      - webnet
    expose:
      - 6379
  web:
    image: sakuru9/music-searcher-api:latest
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 4000:4000
    networks:
      - webnet
    environment:
      REDIS_HOST: redis
    command: sh -c 'node dist/index.js'
networks:
  webnet:
